<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pais;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Pais::create(['nombre' => 'Afghanistan', 'code' => 'AF']);
        Pais::create(['nombre' => 'Albania', 'code' => 'AL']);
        Pais::create(['nombre' => 'Algeria', 'code' => 'DZ']);
        Pais::create(['nombre' => 'American Samoa', 'code' => 'AS']);
        Pais::create(['nombre' => 'Andorra', 'code' => 'AD']);
        Pais::create(['nombre' => 'Angola', 'code' => 'AO']);
        Pais::create(['nombre' => 'Anguilla', 'code' => 'AI']);
        Pais::create(['nombre' => 'Antarctica', 'code' => 'AQ']);
        Pais::create(['nombre' => 'Antigua and Barbuda', 'code' => 'AG']);
        Pais::create(['nombre' => 'Argentina', 'code' => 'AR']);
        Pais::create(['nombre' => 'Armenia', 'code' => 'AM']);
        Pais::create(['nombre' => 'Aruba', 'code' => 'AW']);
        Pais::create(['nombre' => 'Australia', 'code' => 'AU']);
        Pais::create(['nombre' => 'Austria', 'code' => 'AT']);
        Pais::create(['nombre' => 'Azerbaijan', 'code' => 'AZ']);
        Pais::create(['nombre' => 'Bahamas', 'code' => 'BS']);
        Pais::create(['nombre' => 'Bahrain', 'code' => 'BH']);
        Pais::create(['nombre' => 'Bangladesh', 'code' => 'BD']);
        Pais::create(['nombre' => 'Barbados', 'code' => 'BB']);
        Pais::create(['nombre' => 'Belarus', 'code' => 'BY']);
        Pais::create(['nombre' => 'Belgium', 'code' => 'BE']);
        Pais::create(['nombre' => 'Belize', 'code' => 'BZ']);
        Pais::create(['nombre' => 'Benin', 'code' => 'BJ']);
        Pais::create(['nombre' => 'Bermuda', 'code' => 'BM']);
        Pais::create(['nombre' => 'Bhutan', 'code' => 'BT']);
        Pais::create(['nombre' => 'Bolivia', 'code' => 'BO']);
        Pais::create(['nombre' => 'Bonaire', 'code' => 'BQ']);
        Pais::create(['nombre' => 'Bosnia and Herzegovina', 'code' => 'BA']);
        Pais::create(['nombre' => 'Botswana', 'code' => 'BW']);
        Pais::create(['nombre' => 'Bouvet Island', 'code' => 'BV']);
        Pais::create(['nombre' => 'Brazil', 'code' => 'BR']);
        Pais::create(['nombre' => 'Brunei Darussalam', 'code' => 'BN']);
        Pais::create(['nombre' => 'Bulgaria', 'code' => 'BG']);
        Pais::create(['nombre' => 'Burkina Faso', 'code' => 'BF']);
        Pais::create(['nombre' => 'Burundi', 'code' => 'BI']);
        Pais::create(['nombre' => 'Cabo Verde', 'code' => 'CV']);
        Pais::create(['nombre' => 'Cambodia', 'code' => 'KH']);
        Pais::create(['nombre' => 'Cameroon', 'code' => 'CM']);
        Pais::create(['nombre' => 'Canada', 'code' => 'CA']);
        Pais::create(['nombre' => 'Cayman Islands', 'code' => 'KY']);
        Pais::create(['nombre' => 'Central African Republic', 'code' => 'CF']);
        Pais::create(['nombre' => 'Chad', 'code' => 'TD']);
        Pais::create(['nombre' => 'Chile', 'code' => 'CL']);
        Pais::create(['nombre' => 'China', 'code' => 'CN']);
        Pais::create(['nombre' => 'Christmas Island', 'code' => 'CX']);
        Pais::create(['nombre' => 'Cocos Islands', 'code' => 'CC']);
        Pais::create(['nombre' => 'Colombia', 'code' => 'CO']);
        Pais::create(['nombre' => 'Comoros', 'code' => 'KM']);
        Pais::create(['nombre' => 'Congo Democratic Republic', 'code' => 'CD']);
        Pais::create(['nombre' => 'Congo', 'code' => 'CG']);
        Pais::create(['nombre' => 'Cook Islands', 'code' => 'CK']);
        Pais::create(['nombre' => 'Costa Rica', 'code' => 'CR']);
        Pais::create(['nombre' => 'Croatia', 'code' => 'HR']);
        Pais::create(['nombre' => 'Cuba', 'code' => 'CU']);
        Pais::create(['nombre' => 'Curaçao', 'code' => 'CW']);
        Pais::create(['nombre' => 'Cyprus', 'code' => 'CY']);
        Pais::create(['nombre' => 'Czechia', 'code' => 'CZ']);
        Pais::create(['nombre' => 'Côte d\'Ivoire', 'code' => 'CI']);
        Pais::create(['nombre' => 'Denmark', 'code' => 'DK']);
        Pais::create(['nombre' => 'Djibouti', 'code' => 'DJ']);
        Pais::create(['nombre' => 'Dominica', 'code' => 'DM']);
        Pais::create(['nombre' => 'Dominican Republic', 'code' => 'DO']);
        Pais::create(['nombre' => 'Ecuador', 'code' => 'EC']);
        Pais::create(['nombre' => 'Egypt', 'code' => 'EG']);
        Pais::create(['nombre' => 'El Salvador', 'code' => 'SV']);
        Pais::create(['nombre' => 'Equatorial Guinea', 'code' => 'GQ']);
        Pais::create(['nombre' => 'Eritrea', 'code' => 'ER']);
        Pais::create(['nombre' => 'Estonia', 'code' => 'EE']);
        Pais::create(['nombre' => 'Eswatini', 'code' => 'SZ']);
        Pais::create(['nombre' => 'Ethiopia', 'code' => 'ET']);
        Pais::create(['nombre' => 'Falkland Islands', 'code' => 'FK']);
        Pais::create(['nombre' => 'Faroe Islands', 'code' => 'FO']);
        Pais::create(['nombre' => 'Fiji', 'code' => 'FJ']);
        Pais::create(['nombre' => 'Finland', 'code' => 'FI']);
        Pais::create(['nombre' => 'France', 'code' => 'FR']);
        Pais::create(['nombre' => 'French Guiana', 'code' => 'GF']);
        Pais::create(['nombre' => 'French Polynesia', 'code' => 'PF']);
        Pais::create(['nombre' => 'French Southern Territories', 'code' => 'TF']);
        Pais::create(['nombre' => 'Gabon', 'code' => 'GA']);
        Pais::create(['nombre' => 'Gambia', 'code' => 'GM']);
        Pais::create(['nombre' => 'Georgia', 'code' => 'GE']);
        Pais::create(['nombre' => 'Germany', 'code' => 'DE']);
        Pais::create(['nombre' => 'Ghana', 'code' => 'GH']);
        Pais::create(['nombre' => 'Gibraltar', 'code' => 'GI']);
        Pais::create(['nombre' => 'Greece', 'code' => 'GR']);
        Pais::create(['nombre' => 'Greenland', 'code' => 'GL']);
        Pais::create(['nombre' => 'Grenada', 'code' => 'GD']);
        Pais::create(['nombre' => 'Guadeloupe', 'code' => 'GP']);
        Pais::create(['nombre' => 'Guam', 'code' => 'GU']);
        Pais::create(['nombre' => 'Guatemala', 'code' => 'GT']);
        Pais::create(['nombre' => 'Guernsey', 'code' => 'GG']);
        Pais::create(['nombre' => 'Guinea', 'code' => 'GN']);
        Pais::create(['nombre' => 'Guinea-Bissau', 'code' => 'GW']);
        Pais::create(['nombre' => 'Guyana', 'code' => 'GY']);
        Pais::create(['nombre' => 'Haiti', 'code' => 'HT']);
        Pais::create(['nombre' => 'Heard Island and McDonald Islands', 'code' => 'HM']);
        Pais::create(['nombre' => 'Holy See', 'code' => 'VA']);
        Pais::create(['nombre' => 'Honduras', 'code' => 'HN']);
        Pais::create(['nombre' => 'Hong Kong', 'code' => 'HK']);
        Pais::create(['nombre' => 'Hungary', 'code' => 'HU']);
        Pais::create(['nombre' => 'Iceland', 'code' => 'IS']);
        Pais::create(['nombre' => 'India', 'code' => 'IN']);
        Pais::create(['nombre' => 'Indonesia', 'code' => 'ID']);
        Pais::create(['nombre' => 'Iran', 'code' => 'IR']);
        Pais::create(['nombre' => 'Iraq', 'code' => 'IQ']);
        Pais::create(['nombre' => 'Ireland', 'code' => 'IE']);
        Pais::create(['nombre' => 'Isle of Man', 'code' => 'IM']);
        Pais::create(['nombre' => 'Israel', 'code' => 'IL']);
        Pais::create(['nombre' => 'Italy', 'code' => 'IT']);
        Pais::create(['nombre' => 'Jamaica', 'code' => 'JM']);
        Pais::create(['nombre' => 'Japan', 'code' => 'JP']);
        Pais::create(['nombre' => 'Jersey', 'code' => 'JE']);
        Pais::create(['nombre' => 'Jordan', 'code' => 'JO']);
        Pais::create(['nombre' => 'Kazakhstan', 'code' => 'KZ']);
        Pais::create(['nombre' => 'Kenya', 'code' => 'KE']);
        Pais::create(['nombre' => 'Kiribati', 'code' => 'KI']);
        Pais::create(['nombre' => 'Democratic People\'s Republic of Korea', 'code' => 'KP']);
        Pais::create(['nombre' => 'Republic of Korea', 'code' => 'KR']);
        Pais::create(['nombre' => 'Kuwait', 'code' => 'KW']);
        Pais::create(['nombre' => 'Kyrgyzstan', 'code' => 'KG']);
        Pais::create(['nombre' => 'Lao People\'s Democratic Republic', 'code' => 'LA']);
        Pais::create(['nombre' => 'Latvia', 'code' => 'LV']);
        Pais::create(['nombre' => 'Lebanon', 'code' => 'LB']);
        Pais::create(['nombre' => 'Lesotho', 'code' => 'LS']);
        Pais::create(['nombre' => 'Liberia', 'code' => 'LR']);
        Pais::create(['nombre' => 'Libya', 'code' => 'LY']);
        Pais::create(['nombre' => 'Liechtenstein', 'code' => 'LI']);
        Pais::create(['nombre' => 'Lithuania', 'code' => 'LT']);
        Pais::create(['nombre' => 'Luxembourg', 'code' => 'LU']);
        Pais::create(['nombre' => 'Macao', 'code' => 'MO']);
        Pais::create(['nombre' => 'Madagascar', 'code' => 'MG']);
        Pais::create(['nombre' => 'Malawi', 'code' => 'MW']);
        Pais::create(['nombre' => 'Malaysia', 'code' => 'MY']);
        Pais::create(['nombre' => 'Maldives', 'code' => 'MV']);
        Pais::create(['nombre' => 'Mali', 'code' => 'ML']);
        Pais::create(['nombre' => 'Malta', 'code' => 'MT']);
        Pais::create(['nombre' => 'Marshall Islands', 'code' => 'MH']);
        Pais::create(['nombre' => 'Martinique', 'code' => 'MQ']);
        Pais::create(['nombre' => 'Mauritania', 'code' => 'MR']);
        Pais::create(['nombre' => 'Mauritius', 'code' => 'MU']);
        Pais::create(['nombre' => 'Mayotte', 'code' => 'YT']);
        Pais::create(['nombre' => 'Mexico', 'code' => 'MX']);
        Pais::create(['nombre' => 'Micronesia ', 'code' => 'FM']);
        Pais::create(['nombre' => 'Moldova', 'code' => 'MD']);
        Pais::create(['nombre' => 'Monaco', 'code' => 'MC']);
        Pais::create(['nombre' => 'Mongolia', 'code' => 'MN']);
        Pais::create(['nombre' => 'Montenegro', 'code' => 'ME']);
        Pais::create(['nombre' => 'Montserrat', 'code' => 'MS']);
        Pais::create(['nombre' => 'Morocco', 'code' => 'MA']);
        Pais::create(['nombre' => 'Mozambique', 'code' => 'MZ']);
        Pais::create(['nombre' => 'Myanmar', 'code' => 'MM']);
        Pais::create(['nombre' => 'Namibia', 'code' => 'NA']);
        Pais::create(['nombre' => 'Nauru', 'code' => 'NR']);
        Pais::create(['nombre' => 'Nepal', 'code' => 'NP']);
        Pais::create(['nombre' => 'Netherlands', 'code' => 'NL']);
        Pais::create(['nombre' => 'New Caledonia', 'code' => 'NC']);
        Pais::create(['nombre' => 'New Zealand', 'code' => 'NZ']);
        Pais::create(['nombre' => 'Nicaragua', 'code' => 'NI']);
        Pais::create(['nombre' => 'Niger', 'code' => 'NE']);
        Pais::create(['nombre' => 'Nigeria', 'code' => 'NG']);
        Pais::create(['nombre' => 'Niue', 'code' => 'NU']);
        Pais::create(['nombre' => 'Norfolk Island', 'code' => 'NF']);
        Pais::create(['nombre' => 'Northern Mariana Islands', 'code' => 'MP']);
        Pais::create(['nombre' => 'Norway', 'code' => 'NO']);
        Pais::create(['nombre' => 'Oman', 'code' => 'OM']);
        Pais::create(['nombre' => 'Pakistan', 'code' => 'PK']);
        Pais::create(['nombre' => 'Palau', 'code' => 'PW']);
        Pais::create(['nombre' => 'Palestine', 'code' => ' State of', 'code' => 'PS']);
        Pais::create(['nombre' => 'Panama', 'code' => 'PA']);
        Pais::create(['nombre' => 'Papua New Guinea', 'code' => 'PG']);
        Pais::create(['nombre' => 'Paraguay', 'code' => 'PY']);
        Pais::create(['nombre' => 'Peru', 'code' => 'PE']);
        Pais::create(['nombre' => 'Philippines', 'code' => 'PH']);
        Pais::create(['nombre' => 'Pitcairn', 'code' => 'PN']);
        Pais::create(['nombre' => 'Poland', 'code' => 'PL']);
        Pais::create(['nombre' => 'Portugal', 'code' => 'PT']);
        Pais::create(['nombre' => 'Puerto Rico', 'code' => 'PR']);
        Pais::create(['nombre' => 'Qatar', 'code' => 'QA']);
        Pais::create(['nombre' => 'Republic of North Macedonia', 'code' => 'MK']);
        Pais::create(['nombre' => 'Romania', 'code' => 'RO']);
        Pais::create(['nombre' => 'Russian Federation', 'code' => 'RU']);
        Pais::create(['nombre' => 'Rwanda', 'code' => 'RW']);
        Pais::create(['nombre' => 'Réunion', 'code' => 'RE']);
        Pais::create(['nombre' => 'Saint Barthélemy', 'code' => 'BL']);
        Pais::create(['nombre' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH']);
        Pais::create(['nombre' => 'Saint Kitts and Nevis', 'code' => 'KN']);
        Pais::create(['nombre' => 'Saint Lucia', 'code' => 'LC']);
        Pais::create(['nombre' => 'Saint Martin ', 'code' => 'MF']);
        Pais::create(['nombre' => 'Saint Pierre and Miquelon', 'code' => 'PM']);
        Pais::create(['nombre' => 'Saint Vincent and the Grenadines', 'code' => 'VC']);
        Pais::create(['nombre' => 'Samoa', 'code' => 'WS']);
        Pais::create(['nombre' => 'San Marino', 'code' => 'SM']);
        Pais::create(['nombre' => 'Sao Tome and Principe', 'code' => 'ST']);
        Pais::create(['nombre' => 'Saudi Arabia', 'code' => 'SA']);
        Pais::create(['nombre' => 'Senegal', 'code' => 'SN']);
        Pais::create(['nombre' => 'Serbia', 'code' => 'RS']);
        Pais::create(['nombre' => 'Seychelles', 'code' => 'SC']);
        Pais::create(['nombre' => 'Sierra Leone', 'code' => 'SL']);
        Pais::create(['nombre' => 'Singapore', 'code' => 'SG']);
        Pais::create(['nombre' => 'Sint Maarten', 'code' => 'SX']);
        Pais::create(['nombre' => 'Slovakia', 'code' => 'SK']);
        Pais::create(['nombre' => 'Slovenia', 'code' => 'SI']);
        Pais::create(['nombre' => 'Solomon Islands', 'code' => 'SB']);
        Pais::create(['nombre' => 'Somalia', 'code' => 'SO']);
        Pais::create(['nombre' => 'South Africa', 'code' => 'ZA']);
        Pais::create(['nombre' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS']);
        Pais::create(['nombre' => 'South Sudan', 'code' => 'SS']);
        Pais::create(['nombre' => 'Spain', 'code' => 'ES']);
        Pais::create(['nombre' => 'Sri Lanka', 'code' => 'LK']);
        Pais::create(['nombre' => 'Sudan', 'code' => 'SD']);
        Pais::create(['nombre' => 'Suriname', 'code' => 'SR']);
        Pais::create(['nombre' => 'Svalbard and Jan Mayen', 'code' => 'SJ']);
        Pais::create(['nombre' => 'Sweden', 'code' => 'SE']);
        Pais::create(['nombre' => 'Switzerland', 'code' => 'CH']);
        Pais::create(['nombre' => 'Syrian Arab Republic', 'code' => 'SY']);
        Pais::create(['nombre' => 'Taiwan', 'code' => 'TW']);
        Pais::create(['nombre' => 'Tajikistan', 'code' => 'TJ']);
        Pais::create(['nombre' => 'Tanzania', 'code' => 'TZ']);
        Pais::create(['nombre' => 'Thailand', 'code' => 'TH']);
        Pais::create(['nombre' => 'Timor-Leste', 'code' => 'TL']);
        Pais::create(['nombre' => 'Togo', 'code' => 'TG']);
        Pais::create(['nombre' => 'Tokelau', 'code' => 'TK']);
        Pais::create(['nombre' => 'Tonga', 'code' => 'TO']);
        Pais::create(['nombre' => 'Trinidad and Tobago', 'code' => 'TT']);
        Pais::create(['nombre' => 'Tunisia', 'code' => 'TN']);
        Pais::create(['nombre' => 'Turkey', 'code' => 'TR']);
        Pais::create(['nombre' => 'Turkmenistan', 'code' => 'TM']);
        Pais::create(['nombre' => 'Turks and Caicos Islands', 'code' => 'TC']);
        Pais::create(['nombre' => 'Tuvalu', 'code' => 'TV']);
        Pais::create(['nombre' => 'Uganda', 'code' => 'UG']);
        Pais::create(['nombre' => 'Ukraine', 'code' => 'UA']);
        Pais::create(['nombre' => 'United Arab Emirates', 'code' => 'AE']);
        Pais::create(['nombre' => 'United Kingdom of Great Britain and Northern Ireland', 'code' => 'GB']);
        Pais::create(['nombre' => 'United States Minor Outlying Islands', 'code' => 'UM']);
        Pais::create(['nombre' => 'United States of America', 'code' => 'US']);
        Pais::create(['nombre' => 'Uruguay', 'code' => 'UY']);
        Pais::create(['nombre' => 'Uzbekistan', 'code' => 'UZ']);
        Pais::create(['nombre' => 'Vanuatu', 'code' => 'VU']);
        Pais::create(['nombre' => 'Venezuela', 'code' => 'VE']);
        Pais::create(['nombre' => 'Viet Nam', 'code' => 'VN']);
        Pais::create(['nombre' => 'Virgin Islands British', 'code' => 'VG']);
        Pais::create(['nombre' => 'Virgin Islands  U.S.', 'code' => 'VI']);
        Pais::create(['nombre' => 'Wallis and Futuna', 'code' => 'WF']);
        Pais::create(['nombre' => 'Western Sahara', 'code' => 'EH']);
        Pais::create(['nombre' => 'Yemen', 'code' => 'YE']);
        Pais::create(['nombre' => 'Zambia', 'code' => 'ZM']);
        Pais::create(['nombre' => 'Zimbabwe', 'code' => 'ZW']);
        Pais::create(['nombre' => 'Åland Islands', 'code' => 'AX']);
    }
}
